const fs = require("fs");
const path = require("path");
const { createContentPackFromWorkflow } = require("../bridge/workflow_publishing_bridge");
const { autoCreatePublishingQueue } = require("../scheduler/auto_schedule_generator");

function findLatestVideo() {
  const dir = path.join(process.cwd(), "modules", "video-renderer", "output");
  if (!fs.existsSync(dir)) return null;
  return fs.readdirSync(dir)
    .filter(f => f.endsWith(".mp4"))
    .map(f => ({ f, t: fs.statSync(path.join(dir, f)).mtimeMs }))
    .sort((a,b) => b.t - a.t)[0]?.f;
}

const video = findLatestVideo();
const workflowOutput = {
  workflowRunId: `factory_${Date.now()}`,
  channelId: process.env.CHANNEL_ID || "unraaz",
  title: process.env.CONTENT_TITLE || "Auto Factory Content",
  description: process.env.CONTENT_DESC || "Generated by 1 Hub Social Automation factory.",
  hashtags: ["#UNRAAZ", "#Mystery", "#Facts"],
  finalVideoPath: video ? `modules/video-renderer/output/${video}` : null,
  providerTargets: ["telegram", "youtube"]
};

const pack = createContentPackFromWorkflow(workflowOutput);
const schedule = autoCreatePublishingQueue({
  channelId: workflowOutput.channelId,
  providers: ["telegram", "youtube"],
  rules: { timeSlots: ["12:00", "18:00"] }
});

console.log(JSON.stringify({
  success: true,
  phase: "22.4-end-to-end-content-to-publish-wiring",
  mode: "safe-wiring",
  pack,
  schedule
}, null, 2));
